# Run the ssh integration tests with `make sshintegrationtest`.
# These tests can also be running locally.
name: "ssh-integrationtest"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "ssh/**"
      - "tempfork/gliderlabs/ssh/**"
      - ".github/workflows/ssh-integrationtest"
jobs:
  ssh-integrationtest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Run SSH integration tests
        run: |
          make sshintegrationtest