name: tailscale.com/cmd/vet

env:
  HOME: ${{ github.workspace }}
  # GOMODCACHE is the same definition on all OSes. Within the workspace, we use
  # toplevel directories "src" (for the checked out source code), and "gomodcache"
  # and other caches as siblings to follow.
  GOMODCACHE: ${{ github.workspace }}/gomodcache

on:
  push:
    branches:
      - main
      - "release-branch/*"
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  vet:
    runs-on: [ self-hosted, linux ]
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          path: src

      - name: Build 'go vet' tool
        working-directory: src
        run: ./tool/go build -o /tmp/vettool tailscale.com/cmd/vet

      - name: Run 'go vet'
        working-directory: src
        run: ./tool/go vet -vettool=/tmp/vettool tailscale.com/...
